# Generated by Django 3.0.4 on 2020-03-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(unique=True)),
                ('FullName', models.CharField(max_length=250)),
                ('CityName', models.CharField(max_length=150)),
                ('Center', models.CharField(max_length=2, null=True)),
                ('NalSumLimit', models.CharField(max_length=30)),
                ('EngName', models.CharField(max_length=250)),
                ('PostCodeList', models.IntegerField()),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_api.Country')),
                ('OblName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_api.Region')),
            ],
        ),
    ]
