# Generated by Django 3.0.4 on 2020-03-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='Center',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='CityName',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='EngName',
            new_name='eng_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='FullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='NalSumLimit',
            new_name='nal_sum_limit',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='PostCodeList',
            new_name='post_code_list',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='OblName',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='Name',
            new_name='name',
        ),
    ]
