# Generated by Django 3.0.4 on 2020-03-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cdek_code',
            field=models.PositiveIntegerField(verbose_name='CDEK ID'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
